# Welcome to Jekyll!

# Site settings

title: Adiradjapin
tagline: bahan baku pin | material pin
email: adiradjapin@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Kami adalah produsen souvenir dan merchandise, 
  kami menawarkan harga yang terjangkau dengan kualitas terbaik. 
  Kami memproduksi PIN dan gantungan kunci. 
  Selain itu kami juga memproduksi MUG, Pakaian serta 
  berbagai souvenir &amp; merchandise lainnya.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings

markdown: kramdown  
permalink: pretty

port: 8000

exclude: ['layout_design.psd', 'layout_price.psd', 'layout_design.jpg']

sass:
  sass_dir: assets/css