# Images
# ----------------------------------------------

hero: "header-bg.jpg"
footer: "footer-bg.jpg"
logo: "logo.svg"


# Menus
# ----------------------------------------------

menus: 
  - {
      name: pricing,
      url: '#pricing'
    }
  - {
      name: product,
      url: '#product'
    }


# Social Links
# ----------------------------------------------

socials:
  - {
      url: 'https://www.facebook.com/adiradjapin',
      icon: facebook
    }
  - {
      url: 'https://twitter.com/adiradjapin',
      icon: twitter
    }
  - {
      url: 'https://www.instagram.com/adiradjapin/',
      icon: instagram
    }


# Pricing Section
# ----------------------------------------------

lists:
  - {
      list: price,
      name: Daftar Harga,
      tag: 'Bahan Baku',
      file: 'json/price.html'
    }
  - {
      list: order,
      name: Cara Pesan,
      tag: '*Dapatkan harga khusus',
      file: 'json/order.html'
    }